default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: milkyland_development

test:
  <<: *default
  database: milkyland_test

production:
  url: <%= ENV["POSTGRES_URL"] %>
