default: &default
  adapter: trilogy
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: milkyland_development

test:
  <<: *default
  database: milkyland_test

production:
  host: <%= ENV.fetch("MYSQL_HOST", "mysql") %>
  database: milkyland_production
  username: milkyland
  password: <%= ENV.fetch("MYSQL_PASSWORD", "") %>
