service: milkyland

image: seithq/milkyland

ssh:
  user: ubuntu

proxy:
  ssl: true
  host: qr.milkyland.kz

servers:
  web:
    hosts:
      - 194.32.141.210
  job:
    hosts:
      - 194.32.141.210
    cmd: bin/jobs

registry:
  server: ghcr.io
  username: danikarik
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - amd64
  remote: ssh://ubuntu@194.32.141.210
  local: true
  cache:
    type: registry
    image: seithq/milkyland-build-cache
    options: mode=max,oci-mediatypes=true

env:
  secret:
    - RAILS_MASTER_KEY
    - DB_PASSWORD
    - APP_VERSION
    - GIT_REVISION
  clear:
    DB_HOST: milkyland-postgres
    REDIS_URL: redis://milkyland-redis:6379/1
    SOLID_QUEUE_IN_PUMA: false
    JOB_CONCURRENCY: 1
    WEB_CONCURRENCY: 1
    RAILS_LOG_LEVEL: info

accessories:
  postgres:
    image: postgres:15
    roles:
      - web
    port: 5432
    env:
      clear:
        POSTGRES_USER: milkyland
        POSTGRES_DB: milkyland_production
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    roles:
      - web
    port: 6379
    directories:
      - data:/data

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "milkyland-storage:/rails/storage"

asset_path: /rails/public/assets