service: milkyland

image: seithq/milkyland

servers:
  web:
    hosts:
      - 194.67.82.37
  job:
    hosts:
      - 192.168.0.1
    cmd: bin/rails solid_queue:work

registry:
  server: ghcr.io
  username: danikarik
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - MYSQL_PASSWORD
  clear:
    MYSQL_HOST: 194.67.82.37
    REDIS_URL: redis://194.67.82.37/1

asset_path: /rails/public/assets

ssh:
  user: deploy

accessories:
  mysql:
    image: mysql:8.0
    host: 192.168.0.2
    port: 3306
    env:
      clear:
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: milkyland_production
        MYSQL_USER: milkyland
      secret:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_PASSWORD
    files:
      - config/mysql/production.cnf:/etc/mysql/my.cnf
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/mysql
  redis:
    image: redis:7.0
    host: 192.168.0.2
    port: 6379
    directories:
      - data:/data

traefik:
  host_port: 3000
  args:
    accesslog: true
    accesslog.format: json

healthcheck:
  path: /up
  port: 3000