service: milkyland

image: seithq/milkyland

ssh:
  user: deploy

servers:
  web:
    hosts:
      - 194.67.82.37
    labels:
      traefik.http.routers.milkyland-web.rule: Host(`milkyland.okpock.com`)
      traefik.http.routers.milkyland-web-secure.entrypoints: websecure
      traefik.http.routers.milkyland-web-secure.rule: Host(`milkyland.okpock.com`)
      traefik.http.routers.milkyland-web-secure.tls: true
      traefik.http.routers.milkyland-web-secure.tls.certresolver: letsencrypt
    options:
      network: kamal
  job:
    hosts:
      - 194.67.82.37
    cmd: bin/rails solid_queue:work
    options:
      network: kamal

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
    network: kamal
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "daniyar@hey.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

registry:
  server: ghcr.io
  username: danikarik
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  remote:
    arch: amd64
    host: ssh://deploy@194.67.82.37
  cache:
    type: registry
    image: seithq/milkyland-build-cache
    options: mode=max,oci-mediatypes=true

env:
  clear:
    HOST: milkyland.okpock.com
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_URL
    - REDIS_URL
    - APP_VERSION
    - GIT_REVISION

asset_path: /rails/public/assets

accessories:
  postgres:
    image: postgres:15
    roles:
      - web
    port: 5432
    env:
      clear:
        POSTGRES_USER: milkyland
        POSTGRES_DB: milkyland_production
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
    options:
      network: kamal
  redis:
    image: redis:7.0
    roles:
      - web
    port: 6379
    directories:
      - data:/data
    options:
      network: kamal
