default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [ default, mailers, notifications ]
      threads: 3
      processes: 1
      polling_interval: 1

development:
  <<: *default

production:
  <<: *default
